sudo: required
os:
# Travis' Mac OS X python environment is broken due to SSL include problems.
# We're hence bootstrapping regular containers.
# 
# Linux testing temporarily disabled due to version conflict in
# `six` dependencies (1.5 vs. 1.6)
#   - linux
  - osx
dist: trusty

language: generic

# build dependencies
install:
  - pwd
  - ls -alR
  - bootstrap/bootstrap.sh
  # Fix openssl / python hashlib on OS X Travis CI
  - if which brew &>/dev/null ; then export LDFLAGS=-L/usr/local/opt/openssl/lib CPPFLAGS=-I/usr/local/opt/openssl/include PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig ; fi

# command to run tests, takes care of python dependencies
script: python setup.py test
